@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}

### Route GET /cocktails

GET {{baseUrl}}/cocktails

### Route GET /cocktails/{id}

GET {{baseUrl}}/cocktails/3

### Route GET /cocktails/{mauvaise id}

GET {{baseUrl}}/cocktails/2

### Route POST /cocktails

POST {{baseUrl}}/cocktails
Content-Type: application/json

{
   "name": "mojit",
   "type": "long drink",
   "ingredients":"rhum menthe citron vert sucre roux eaux gazeuze ",
   "labels": "rhum",
   "note": 2
}

### Route DELETE /cocktails/
DELETE  {{baseUrl}}/cocktails/10

#### PATCH /cocktails
PATCH  {{baseUrl}}/cocktails/13
Content-Type: application/json

{
   "name": "teste"
}