@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}

### Route GET /cocktails

GET {{baseUrl}}/cocktails

### Route GET /cocktails/{id}

GET {{baseUrl}}/cocktails/1

### Route GET /cocktails/{mauvaise id}

GET {{baseUrl}}/cocktails/2
